# Generated by Django 2.2.13 on 2021-08-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210813_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default=' image.jpg', upload_to='clients'),
        ),
    ]
